library(shiny)    

d <- read.csv("toweb_2018.csv")    # read in data

shinyServer(function(input, output) {
  
  options = reactiveValues(choose="")   # creates the object 'options'

    observeEvent(input$go,{
    name_link = switch(input$variable, "Violent Crime"="viol", "Property Crime"="prop")
    options$choose = paste(name_link, substr(input$year,1,4), sep="")
    choice = d[,grep(options$choose, colnames(d))]
    output$hist <- renderPlot({
      hist(choice, xlab=NULL, breaks=15, col="dodgerblue", 
           ylab="# of Cities", border="white", main=paste(input$year, input$variable, sep=" "))
      abline(v=d[,grep(options$choose, colnames(d))][d$CITY==input$city], lwd=2) 
      abline(v=mean(choice, na.rm=T), lty=2)
      box()
      if(input$year=="2018"){position <- "topright"} else{position <- "topleft"}
      legend(position, inset=0.05, c(input$city, "Avg of All Cities"), lwd=c(2,1), lty=c(1,2), bty="n")
    })
    
    output$data1 <- renderPrint({
      paste(input$city, " ", input$variable, " ", input$year, ": ", d[,grep(options$choose, colnames(d))][d$CITY==input$city],
            " (", round(ecdf(choice[!is.na(choice)])(d[,grep(options$choose, colnames(d))][d$CITY==input$city]),4), " percentile)", sep="")
    })
    
    output$data2 <- renderPrint({
      summary(choice)
    })
  })

    output$var_desc <- renderText({
      data_link = switch(input$variable,
                       "Property Crime" = "is the number of nonviolent crimes including burglary, motor vehicle theft, and larceny per 100,000 population.",
                       "Violent Crime"= "is the number of violent crimes including aggravated assault, robbery, and homicide per 100,000 population. ")
      paste(input$variable, data_link)
    })
    
    output$yr_desc <- renderText({
      yr_link = switch(input$year, 
                       "2018" = "figures show a predicted crime rate for 2018.  These values are generated by ILSSC based on a model using the trend in crime over the last 15 years.
                       The forecasted value has a degree of uncertainty, but is the model's 'best guess' for the level of crime in 2018.",
                       "Change, 2016-2018" = "presents the difference in the predicted crime rate in 2018 compared to the actual crime rate in 2016.")
      paste(input$year, yr_link)
    })
    
})  

