library(shiny)    

d <- read.csv("toweb_2015.csv")    # read in data

descr = data.frame(c("Violent Crime", "Property Crime"),
                   c("is a predicted rate for violent crimes (including XXX) generated by ILSCC blah blah blah...",
                     "is a predicted rate for nonviolent crimes (including XXX) generated by ILSCC blah blah blah..."))
colnames(descr) = c("var", "explain")   

shinyServer(function(input, output) {
  
  options = reactiveValues(choose="")   # creates the object 'options'
  observeEvent(input$go, {
    name_link = switch(input$variable, "Violent Crime"="viol", "Property Crime"="prop")
    options$choose = paste(name_link, substr(input$year,1,4), sep="")
  })
  
  observeEvent(input$go,{
    choice = d[,grep(options$choose, colnames(d))]
    output$hist <- renderPlot({
      hist(choice, xlab=NULL, breaks=15, col="dodgerblue", 
           ylab="# of Cities", border="white", main=paste(input$year, input$variable, sep=" "))
      abline(v=d[,grep(options$choose, colnames(d))][d$CITY==input$city], lwd=2) 
      abline(v=mean(choice, na.rm=T), lty=2)
      box()
      if(input$year=="2017"){position <- "topright"} else{position <- "topleft"}
      legend(position, inset=0.05, c(input$city, "Avg of All Cities"), lwd=c(2,1), lty=c(1,2), bty="n")
    })
    
    output$data1 <- renderPrint({
      paste(input$city, " ", input$variable, " ", input$year, ": ", d[,grep(options$choose, colnames(d))][d$CITY==input$city],
            " (", round(ecdf(choice[!is.na(choice)])(d[,grep(options$choose, colnames(d))][d$CITY==input$city]),4), " percentile)", sep="")
    })
    
    output$data2 <- renderPrint({
      summary(choice)
    })
  })

    output$var_desc <- renderText({
      data_link = switch(input$variable,
                       "Violent Crime" = descr$explain[descr$var=="Violent Crime"],
                       "Property Crime"= descr$explain[descr$var=="Property Crime"])
      paste(input$variable, data_link)
    })
})  

